version: "3"

services:

  mysql:
    container_name: mysqldb
    image: mysql
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_DATABASE: user_security
      MYSQL_USER: zeljko
      MYSQL_PASSWORD: zeljkoo123
      MYSQL_ROOT_PASSWORD: zeljkoo123
    volumes:
      - mysql-data:/var/lib/mysql

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

volumes:
  mysql-data:
  cache:
      driver: local
