version: "3"

services:

  mysql:
    container_name: mysqldb
    image: mysql
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_DATABASE: user_security
      MYSQL_USER: zeljko
      MYSQL_PASSWORD: zeljkoo123
      MYSQL_ROOT_PASSWORD: zeljkoo123
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
